#!/usr/bin/with-contenv bash

if [ ! -d /usr/lib/python3.8/site-packages/influxdb ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Gilbn'
  echo '| Running installation of required modules for geoip2influx'
  echo '------------------------------------------------------------------------'
  pip3 install --no-cache-dir -U \
    geoip2 \
    geohash2 \
    influxdb \
    IPy 
fi

if [ ! -f /config/geoip2db ]; then
  mkdir /config/geoip2db
fi
echo '------------------------------------------------------------------------'
echo '| Copying geoip2influx.py to /config/geoip2db/'
echo '------------------------------------------------------------------------'
cp /geoip2-mod/geoip2influx.py /config/geoip2db/
chmod +x /config/geoip2db/geoip2influx.py
